apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: dvna
  name: dvna
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dvna
    spec:
      containers:
      - image: dvna
        name: dvna
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
